from __future__ import annotations

from pce.editor.panels.workspaces import normalize_workspace


ACTION_FIELD_TAGS = {
    "actions_header",
    "action_list",
    "action_buttons",
    "recipe_template",
    "preview_interaction_button",
    "action_warning_text",
    "action_type",
    "action_speaker",
    "action_text",
    "action_item",
    "action_object",
    "action_variable",
    "action_value",
    "action_enabled",
    "action_npc",
    "action_node",
    "action_scene",
    "action_spawn",
    "action_condition_header",
    "action_condition_type",
    "action_condition_variable",
    "action_condition_operator",
    "action_condition_value",
    "action_condition_item",
    "action_condition_object",
    "action_condition_not_type",
    "action_actions_header",
    "action_actions_list",
    "action_actions_buttons",
    "action_if_actions_header",
    "action_if_actions_list",
    "action_if_actions_buttons",
    "action_else_actions_header",
    "action_else_actions_list",
    "action_else_actions_buttons",
    "action_condition_json",
    "action_actions_json",
    "action_if_actions_json",
    "action_else_actions_json",
    "apply_action_button",
}

DIALOGUE_FIELD_TAGS = {
    "dialogue_header",
    "dialogue_composer",
    "dialogue_composer_toolbar",
    "dialogue_composer_add_line",
    "dialogue_composer_preview",
    "dialogue_composer_validation",
    "dialogue_composer_panel",
    "dialogue_composer_graph_header",
    "dialogue_graph_overview",
    "dialogue_node_list",
    "dialogue_buttons",
    "dialogue_node_id",
    "dialogue_speaker",
    "dialogue_text",
    "dialogue_node_actions_header",
    "dialogue_node_action_list",
    "dialogue_node_action_buttons",
    "dialogue_node_actions_json",
    "dialogue_choice_list",
    "dialogue_choice_buttons",
    "dialogue_choice_text",
    "dialogue_choice_target",
    "dialogue_choice_condition_header",
    "dialogue_choice_condition_type",
    "dialogue_choice_condition_variable",
    "dialogue_choice_condition_operator",
    "dialogue_choice_condition_value",
    "dialogue_choice_condition_item",
    "dialogue_choice_condition_object",
    "dialogue_choice_condition_not_type",
    "dialogue_choice_actions_header",
    "dialogue_choice_action_list",
    "dialogue_choice_action_buttons",
    "dialogue_choice_condition_json",
    "dialogue_choice_actions_json",
    "apply_dialogue_node_button",
    "apply_choice_button",
}

ADVANCED_FIELD_TAGS = {
    "prop_id",
    "prop_layer",
    "action_condition_header",
    "action_condition_type",
    "action_condition_variable",
    "action_condition_operator",
    "action_condition_value",
    "action_condition_item",
    "action_condition_object",
    "action_condition_not_type",
    "action_condition_json",
    "action_actions_json",
    "action_if_actions_json",
    "action_else_actions_json",
    "action_actions_header",
    "action_actions_list",
    "action_actions_buttons",
    "action_if_actions_header",
    "action_if_actions_list",
    "action_if_actions_buttons",
    "action_else_actions_header",
    "action_else_actions_list",
    "action_else_actions_buttons",
    "dialogue_node_id",
    "dialogue_node_actions_header",
    "dialogue_node_action_list",
    "dialogue_node_action_buttons",
    "dialogue_node_actions_json",
    "dialogue_choice_condition_header",
    "dialogue_choice_condition_type",
    "dialogue_choice_condition_variable",
    "dialogue_choice_condition_operator",
    "dialogue_choice_condition_value",
    "dialogue_choice_condition_item",
    "dialogue_choice_condition_object",
    "dialogue_choice_condition_not_type",
    "dialogue_choice_actions_header",
    "dialogue_choice_action_list",
    "dialogue_choice_action_buttons",
    "dialogue_choice_condition_json",
    "dialogue_choice_actions_json",
    "apply_properties_button",
    "apply_action_button",
    "apply_dialogue_node_button",
    "apply_choice_button",
}

STRUCTURE_TAGS = {
    "context_empty_state",
    "context_scene_tools",
    "context_primary_properties_header",
    "context_primary_properties",
    "context_interactions_header",
    "context_dialogue_header",
    "expert_drawer",
}


def inspector_field_visibility(
    kind: str | None,
    has_item: bool,
    *,
    workspace: str = "Build",
    advanced: bool = False,
) -> dict[str, bool]:
    active_workspace = normalize_workspace(workspace)
    build_workspace = active_workspace == "Build"
    dialogue_workspace = active_workspace == "Dialogue"
    action_owner = kind in {"hotspot", "npc", "item"}
    dialogue_owner = kind == "npc"
    scene_selected = kind == "scene"
    visibility = {
        "context_empty_state": not has_item,
        "context_scene_tools": scene_selected and build_workspace,
        "context_primary_properties_header": has_item and active_workspace != "Check",
        "context_primary_properties": has_item and active_workspace != "Check",
        "context_interactions_header": action_owner and build_workspace,
        "context_dialogue_header": dialogue_owner and build_workspace,
        "expert_drawer": has_item and advanced,
        "prop_id": has_item and active_workspace != "Check",
        "prop_name": has_item and kind in {"scene", "hotspot", "exit", "npc"} and active_workspace != "Check",
        "prop_rect": kind in {"hotspot", "exit", "item"} and build_workspace,
        "prop_pos": kind in {"npc", "spawn"} and active_workspace != "Check",
        "prop_background": scene_selected and build_workspace,
        "background_button": scene_selected and build_workspace,
        "prop_sprite": kind == "npc" and active_workspace != "Check",
        "npc_sprite_button": kind == "npc" and build_workspace,
        "player_sprite_button": scene_selected and build_workspace,
        "prop_item_id": kind == "item" and build_workspace,
        "prop_enabled": kind in {"hotspot", "item"} and build_workspace,
        "prop_layer": kind in {"hotspot", "exit", "item"} and build_workspace,
        "prop_facing": kind == "spawn",
        "prop_target_scene": False,
        "prop_target_scene_card": kind == "exit" and build_workspace,
        "prop_target_spawn": kind == "exit" and build_workspace,
        "preview_exit_button": kind == "exit" and build_workspace,
        "exit_warning_text": kind == "exit" and build_workspace,
        "prop_walk_path": kind == "exit" and build_workspace,
        "prop_lines": kind == "npc" and active_workspace != "Check",
        "duplicate_button": has_item and not scene_selected and build_workspace,
        "delete_button": has_item and not scene_selected and build_workspace,
        "actions_header": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "recipe_template": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_list": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_buttons": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "preview_interaction_button": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_warning_text": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_type": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_speaker": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_text": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_item": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_object": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_variable": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_value": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_enabled": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_npc": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_node": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_scene": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_spawn": action_owner and (build_workspace or (dialogue_workspace and advanced)),
        "action_condition_header": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_type": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_variable": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_operator": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_value": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_item": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_object": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_not_type": action_owner and (build_workspace or dialogue_workspace),
        "action_actions_header": action_owner and (build_workspace or dialogue_workspace),
        "action_actions_list": action_owner and (build_workspace or dialogue_workspace),
        "action_actions_buttons": action_owner and (build_workspace or dialogue_workspace),
        "action_if_actions_header": action_owner and (build_workspace or dialogue_workspace),
        "action_if_actions_list": action_owner and (build_workspace or dialogue_workspace),
        "action_if_actions_buttons": action_owner and (build_workspace or dialogue_workspace),
        "action_else_actions_header": action_owner and (build_workspace or dialogue_workspace),
        "action_else_actions_list": action_owner and (build_workspace or dialogue_workspace),
        "action_else_actions_buttons": action_owner and (build_workspace or dialogue_workspace),
        "action_condition_json": False,
        "action_actions_json": False,
        "action_if_actions_json": False,
        "action_else_actions_json": False,
        "apply_action_button": action_owner and advanced and (build_workspace or dialogue_workspace),
        "dialogue_header": dialogue_owner and dialogue_workspace,
        "dialogue_composer": dialogue_owner and dialogue_workspace,
        "dialogue_composer_toolbar": dialogue_owner and dialogue_workspace,
        "dialogue_composer_add_line": dialogue_owner and dialogue_workspace,
        "dialogue_composer_preview": dialogue_owner and dialogue_workspace,
        "dialogue_composer_validation": dialogue_owner and dialogue_workspace,
        "dialogue_composer_panel": dialogue_owner and dialogue_workspace,
        "dialogue_composer_graph_header": dialogue_owner and dialogue_workspace,
        "dialogue_graph_overview": dialogue_owner and dialogue_workspace,
        "dialogue_node_list": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_buttons": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_node_id": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_speaker": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_text": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_node_actions_header": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_node_action_list": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_node_action_buttons": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_node_actions_json": False,
        "dialogue_choice_list": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_buttons": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_text": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_target": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_header": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_type": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_variable": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_operator": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_value": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_item": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_object": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_not_type": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_actions_header": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_action_list": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_action_buttons": dialogue_owner and dialogue_workspace and advanced,
        "dialogue_choice_condition_json": False,
        "dialogue_choice_actions_json": False,
        "apply_dialogue_node_button": dialogue_owner and dialogue_workspace and advanced,
        "apply_choice_button": dialogue_owner and dialogue_workspace and advanced,
        "apply_properties_button": has_item and advanced and active_workspace != "Check",
        "edit_interaction_button": False,
        "edit_conversation_button": dialogue_owner and build_workspace,
        "dialogue_workspace_hint": dialogue_owner and build_workspace,
    }

    if not advanced:
        for tag in ADVANCED_FIELD_TAGS:
            visibility[tag] = False

    return visibility
