from __future__ import annotations


def inspector_field_visibility(kind: str | None, has_item: bool) -> dict[str, bool]:
    action_owner = kind in {"hotspot", "npc", "item"}
    return {
        "prop_id": has_item,
        "prop_name": has_item and kind in {"scene", "hotspot", "exit", "npc"},
        "prop_rect": kind in {"hotspot", "exit", "item"},
        "prop_pos": kind in {"npc", "spawn"},
        "prop_background": kind == "scene",
        "background_button": kind == "scene",
        "prop_sprite": kind == "npc",
        "npc_sprite_button": kind == "npc",
        "player_sprite_button": kind == "scene",
        "prop_item_id": kind == "item",
        "prop_enabled": kind in {"hotspot", "item"},
        "prop_layer": kind in {"hotspot", "exit", "item"},
        "prop_facing": kind == "spawn",
        "prop_target_scene": kind == "exit",
        "prop_target_spawn": kind == "exit",
        "prop_walk_path": kind == "exit",
        "prop_lines": kind == "npc",
        "duplicate_button": kind is not None,
        "delete_button": kind is not None,
        "actions_header": action_owner,
        "action_list": action_owner,
        "action_buttons": action_owner,
        "action_type": action_owner,
        "action_speaker": action_owner,
        "action_text": action_owner,
        "action_item": action_owner,
        "action_object": action_owner,
        "action_variable": action_owner,
        "action_value": action_owner,
        "action_enabled": action_owner,
        "action_npc": action_owner,
        "action_node": action_owner,
        "action_scene": action_owner,
        "action_spawn": action_owner,
        "action_condition_json": action_owner,
        "action_actions_json": action_owner,
        "action_if_actions_json": action_owner,
        "action_else_actions_json": action_owner,
        "dialogue_header": kind == "npc",
        "dialogue_node_list": kind == "npc",
        "dialogue_buttons": kind == "npc",
        "dialogue_node_id": kind == "npc",
        "dialogue_speaker": kind == "npc",
        "dialogue_text": kind == "npc",
        "dialogue_node_actions_json": kind == "npc",
        "dialogue_choice_list": kind == "npc",
        "dialogue_choice_buttons": kind == "npc",
        "dialogue_choice_text": kind == "npc",
        "dialogue_choice_target": kind == "npc",
        "dialogue_choice_condition_json": kind == "npc",
        "dialogue_choice_actions_json": kind == "npc",
    }
